# Preprocessing

# importing libraries

In [16]:
import numpy as np
import pandas as pd

# importing dataset

In [17]:
dataset = pd.read_csv('data.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [18]:
print(X)

[['India' 44.0 72000.0]
 ['Bangladesh' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Bangladesh' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['Bangladesh' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['Bangladesh' 37.0 67000.0]]


In [19]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


# taking care of missing values

In [20]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:, 1:3])
X[:, 1:3] = imputer.transform(X[:, 1:3])

In [21]:
print(X)

[['India' 44.0 72000.0]
 ['Bangladesh' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Bangladesh' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['Bangladesh' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['Bangladesh' 37.0 67000.0]]


# taking care of non-numerical values

# independent variables

In [22]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [23]:
print(X)

[[0.0 0.0 0.0 1.0 0.0 44.0 72000.0]
 [1.0 0.0 0.0 0.0 0.0 27.0 48000.0]
 [0.0 0.0 1.0 0.0 0.0 30.0 54000.0]
 [0.0 0.0 0.0 0.0 1.0 38.0 61000.0]
 [1.0 0.0 0.0 0.0 0.0 40.0 63777.77777777778]
 [0.0 1.0 0.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 0.0 0.0 48.0 79000.0]
 [0.0 0.0 1.0 0.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 0.0 0.0 37.0 67000.0]]


# dependent variable

In [24]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [25]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


# test train split

In [26]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

In [27]:
print(X_test)

[[0.0 0.0 0.0 0.0 1.0 38.0 61000.0]
 [1.0 0.0 0.0 0.0 0.0 27.0 48000.0]]


In [28]:
print(y_test)

[0 1]


# stanndard scaling

In [29]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:, 5:] = sc.fit_transform(X_train[:, 5:])
X_test[:, 5:] = sc.transform(X_test[:, 5:])

In [30]:
print(X_train)

[[0.0 0.0 0.0 1.0 0.0 0.5825559963215406 0.5553288111488088]
 [0.0 0.0 0.0 0.0 1.0 -0.2502997246552624 -1.3262558666259776]
 [1.0 0.0 0.0 0.0 0.0 -0.05537604527771285 -0.21821155638082532]
 [0.0 0.0 1.0 0.0 0.0 1.5394540587204208 1.5902003839249412]
 [0.0 1.0 0.0 0.0 0.0 -0.8527910972767797 -0.7617804632935417]
 [1.0 0.0 0.0 0.0 0.0 1.220488037920794 1.213883448369984]
 [1.0 0.0 0.0 0.0 0.0 -0.5338250764771529 0.0849326417051122]
 [0.0 0.0 1.0 0.0 0.0 -1.6502061492758466 -1.138097398848499]]
