# Preprocessing

# importing libraries

In [2]:
import numpy as np
import pandas as pd

# importing dataset

In [3]:
dataset = pd.read_csv('data.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [5]:
print(X)

[['India' 44.0 72000.0]
 ['Bangladesh' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Bangladesh' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['Bangladesh' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['Bangladesh' 37.0 67000.0]]


In [6]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


# taking care of missing values

In [7]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:, 1:3])
X[:, 1:3] = imputer.transform(X[:, 1:3])

In [9]:
print(X)

[['India' 44.0 72000.0]
 ['Bangladesh' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Bangladesh' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['Bangladesh' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['Bangladesh' 37.0 67000.0]]


# taking care of non-numerical values

# independent variables

In [11]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [12]:
print(X)

[[1.0 0.0 0.0 0.0 1.0 0.0 44.0 72000.0]
 [0.0 1.0 0.0 0.0 0.0 0.0 27.0 48000.0]
 [1.0 0.0 0.0 1.0 0.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 0.0 0.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 1.0 0.0 0.0 0.0 35.0 58000.0]
 [1.0 0.0 0.0 0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 0.0 0.0 0.0 48.0 79000.0]
 [1.0 0.0 0.0 1.0 0.0 0.0 50.0 83000.0]
 [0.0 1.0 0.0 0.0 0.0 0.0 37.0 67000.0]]


# dependent variable

In [13]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [14]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


# test train split

In [20]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

In [22]:
print(X_test)

[[1.0 0.0 1.0 0.0 0.0 0.0 35.0 58000.0]
 [1.0 0.0 0.0 0.0 0.0 1.0 38.0 61000.0]]


In [23]:
print(y_test)

[1 0]


# stanndard scaling

In [24]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:, 3:] = sc.fit_transform(X_train[:, 3:])
X_test[:, 3:] = sc.transform(X_test[:, 3:])

In [26]:
print(X_train)

[[0.0 1.0 0.0 -0.5773502691896258 -0.3779644730092272 -0.3779644730092272
  1.1459817670979646 1.1787296241694332]
 [1.0 0.0 0.0 -0.5773502691896258 -0.3779644730092272 2.6457513110645903
  -0.07541774069184015 -1.0699949974060108]
 [0.0 1.0 0.0 -0.5773502691896258 -0.3779644730092272 -0.3779644730092272
  0.08645448323210979 -0.08906985383812147]
 [1.0 0.0 0.0 1.7320508075688774 -0.3779644730092272 -0.3779644730092272
  -1.2379546216002089 -0.9034228032152373]
 [1.0 0.0 0.0 -0.5773502691896258 2.6457513110645903 -0.3779644730092272
  0.6162181251650373 0.5957269445017254]
 [0.0 1.0 0.0 -0.5773502691896258 -0.3779644730092272 -0.3779644730092272
  -0.3108682482175858 0.17929645902479133]
 [1.0 0.0 0.0 1.7320508075688774 -0.3779644730092272 -0.3779644730092272
  1.4108635880644285 1.5118740125509804]
 [0.0 1.0 0.0 -0.5773502691896258 -0.3779644730092272 -0.3779644730092272
  -1.6352773530499045 -1.403139385787558]]
