# multiple linear regression

# importing libraries

In [1]:
import numpy as np

# importing dataset

In [2]:
import pandas as pd
dataset = pd.read_csv('startups data.csv')
dataset

Misc Spend  Administration Spend  Marketing Spend      State     Profit
0    165349.20             136897.80        471784.10      Bihar  192261.83
1    162597.70             151377.59        443898.53  Karnataka  191792.06
2    153441.51             101145.55        407934.54     Kerala  191050.39
3    144372.41             118671.85        383199.62      Bihar  182901.99
4    142107.34              91391.77        366168.42     Kerala  166187.94
5    131876.90              99814.71        362861.36      Bihar  156991.12
6    134615.46             147198.87        127716.82  Karnataka  156122.51
7    130298.13             145530.06        323876.68     Kerala  155752.60
8    120542.52             148718.95        311613.29      Bihar  152211.77
9    123334.88             108679.17        304981.62  Karnataka  149759.96
10   101913.08             110594.11        229160.95     Kerala  146121.95
11   100671.96              91790.61        249744.55  Karnataka  144259.40
12    93863.75             127320.38        249839.44     Kerala  141585.52
13    91992.39             135495.07        252664.93  Karnataka  134307.35
14   119943.24             156547.42        256512.92     Kerala  132602.65
15   114523.61             122616.84        261776.23      Bihar  129917.04
16    78013.11             121597.55        264346.06  Karnataka  126992.93
17    94657.16             145077.58        282574.31      Bihar  125370.37
18    91749.16             114175.79        294919.57     Kerala  124266.90
19    86419.70             153514.11             0.00      Bihar  122776.86
20    76253.86             113867.30        298664.47  Karnataka  118474.03
21    78389.47             153773.43        299737.29      Bihar  111313.02
22    73994.56             122782.75        303319.26     Kerala  110352.25
23    67532.53             105751.03        304768.73     Kerala  108733.99
24    77044.01              99281.34        140574.81      Bihar  108552.04
25    64664.71             139553.16        137962.62  Karnataka  107404.34
26    75328.87             144135.98        134050.07     Kerala  105733.54
27    72107.60             127864.55        353183.81      Bihar  105008.31
28    66051.52             182645.56        118148.20     Kerala  103282.38
29    65605.48             153032.06        107138.38      Bihar  101004.64
30    61994.48             115641.28         91131.24     Kerala   99937.59
31    61136.38             152701.92         88218.23      Bihar   97483.56
32    63408.86             129219.61         46085.25  Karnataka   97427.84
33    55493.95             103057.49        214634.81     Kerala   96778.92
34    46426.07             157693.92        210797.67  Karnataka   96712.80
35    46014.02              85047.44        205517.64      Bihar   96479.51
36    28663.76             127056.21        201126.82     Kerala   90708.19
37    44069.95              51283.14        197029.42  Karnataka   89949.14
38    20229.59              65947.93        185265.10      Bihar   81229.06
39    38558.51              82982.09        174999.30  Karnataka   81005.76
40    28754.33             118546.05        172795.67  Karnataka   78239.91
41    27892.92              84710.77        164470.71     Kerala   77798.83
42    23640.93              96189.63        148001.11  Karnataka   71498.49
43    15505.73             127382.30         35534.17      Bihar   69758.98
44    22177.74             154806.14         28334.72  Karnataka   65200.33
45     1000.23             124153.04          1903.93      Bihar   64926.08
46     1315.46             115816.21        297114.46     Kerala   49490.75
47        0.00             135426.92             0.00  Karnataka   42559.73
48      542.05              51743.15             0.00      Bihar   35673.41
49        0.00             116983.80         45173.06  Karnataka   14681.40

In [3]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [4]:
print(X)

[[165349.2 136897.8 471784.1 'Bihar']
 [162597.7 151377.59 443898.53 'Karnataka']
 [153441.51 101145.55 407934.54 'Kerala']
 [144372.41 118671.85 383199.62 'Bihar']
 [142107.34 91391.77 366168.42 'Kerala']
 [131876.9 99814.71 362861.36 'Bihar']
 [134615.46 147198.87 127716.82 'Karnataka']
 [130298.13 145530.06 323876.68 'Kerala']
 [120542.52 148718.95 311613.29 'Bihar']
 [123334.88 108679.17 304981.62 'Karnataka']
 [101913.08 110594.11 229160.95 'Kerala']
 [100671.96 91790.61 249744.55 'Karnataka']
 [93863.75 127320.38 249839.44 'Kerala']
 [91992.39 135495.07 252664.93 'Karnataka']
 [119943.24 156547.42 256512.92 'Kerala']
 [114523.61 122616.84 261776.23 'Bihar']
 [78013.11 121597.55 264346.06 'Karnataka']
 [94657.16 145077.58 282574.31 'Bihar']
 [91749.16 114175.79 294919.57 'Kerala']
 [86419.7 153514.11 0.0 'Bihar']
 [76253.86 113867.3 298664.47 'Karnataka']
 [78389.47 153773.43 299737.29 'Bihar']
 [73994.56 122782.75 303319.26 'Kerala']
 [67532.53 105751.03 304768.73 'Kerala']
 [770

# taking care of non-numerical data

In [5]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [3])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [6]:
print(X)

[[1.0 0.0 0.0 165349.2 136897.8 471784.1]
 [0.0 1.0 0.0 162597.7 151377.59 443898.53]
 [0.0 0.0 1.0 153441.51 101145.55 407934.54]
 [1.0 0.0 0.0 144372.41 118671.85 383199.62]
 [0.0 0.0 1.0 142107.34 91391.77 366168.42]
 [1.0 0.0 0.0 131876.9 99814.71 362861.36]
 [0.0 1.0 0.0 134615.46 147198.87 127716.82]
 [0.0 0.0 1.0 130298.13 145530.06 323876.68]
 [1.0 0.0 0.0 120542.52 148718.95 311613.29]
 [0.0 1.0 0.0 123334.88 108679.17 304981.62]
 [0.0 0.0 1.0 101913.08 110594.11 229160.95]
 [0.0 1.0 0.0 100671.96 91790.61 249744.55]
 [0.0 0.0 1.0 93863.75 127320.38 249839.44]
 [0.0 1.0 0.0 91992.39 135495.07 252664.93]
 [0.0 0.0 1.0 119943.24 156547.42 256512.92]
 [1.0 0.0 0.0 114523.61 122616.84 261776.23]
 [0.0 1.0 0.0 78013.11 121597.55 264346.06]
 [1.0 0.0 0.0 94657.16 145077.58 282574.31]
 [0.0 0.0 1.0 91749.16 114175.79 294919.57]
 [1.0 0.0 0.0 86419.7 153514.11 0.0]
 [0.0 1.0 0.0 76253.86 113867.3 298664.47]
 [1.0 0.0 0.0 78389.47 153773.43 299737.29]
 [0.0 0.0 1.0 73994.56 122782.75 3

# splitting dataset into train and test sets

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=0)


# training model

In [8]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression()

# predicting results

In [9]:
y_pred = regressor.predict(X_test)

In [10]:
[[y_test[i], y_pred[i]] for i in range(len(y_test))]

[[103282.38, 103015.20159798024],
 [144259.4, 132582.2776081392],
 [146121.95, 132447.73845173416],
 [77798.83, 71976.09851260015],
 [191050.39, 178537.4822104868],
 [105008.31, 116161.24230161439],
 [81229.06, 67851.69209677525],
 [97483.56, 98791.73374690354],
 [110352.25, 113969.43533009994],
 [166187.94, 167921.0656954535]]

In [11]:
# accuracy
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.9347068473282101